version: "3.8"

services:
  # Main application service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: docker-learning-server
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=docker
      - PORT=3000
    volumes:
      # Mount source code for development (comment out for production)
      - .:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
